### ISSUE TITLE
Reorganise main DB Python script

### ISSUE THREAD

**Issue by asingh80** [abdulkhalil54/Team-Sun#19]
**Task:** Reorganise main DB Python script. Chinguun has already laid the groundwork for this in the same Python script. 
- Fill up the current functions (delete / create / populate) with the appropriate commands for all the tables. (Refer to the database tables schema under Documentation.)
- Create functions which will facilitate testing (e.g. creating dummy tables, filling them up with dummy values, resetting the tables after testing). 
- Consult back-end meeting notes / post in back-end channel on Discord as required.

**Deadline:** Apr 25.

**Comment by ChilliCreek** [comment]
The script has been created, and basic functions are available to administer the Database
