### ISSUE TITLE
Registration Page HTML/CSS

### ISSUE THREAD

**Issue by linlinnilnil** [abdulkhalil54/Team-Sun#22]
- [x] Create HTML/CSS For Registration Page
- [x]  Enforce string limit restrictions.
- [x] Add email field. Character limit: 100 characters.

**Comment by ChilliCreek** [comment]
Please notify everybody when it is done

**Comment by linlinnilnil** [comment]
HTML/CSS Has been created. Please comment on this task and notify on Discord on any feedback/ additional requirements needed

**Comment by linlinnilnil** [comment]
Enforce string limits on registration fields.

**Comment by DarzyD** [comment]
Added email fields
