### ISSUE TITLE
Registration Page JS/Backend

### ISSUE THREAD

**Issue by linlinnilnil** [abdulkhalil54/Team-Sun#23]
The whole team shall work with Chinguun as the passenger.
- [x] Come up with the specifications for the backend API first.
- [x] Create routers and controllers to execute queries and send responses back.
- [x]  Write the queries to the controllers to retrieve necessary information for the database.
- [x] Test using Postman
- [x] Test using requests from frontend.

**Comment by asingh80** [comment]
With Chinguun's help, the first four tasks have been completed. Once the front-end + back-end Registration progress has been merged on GitHub, this can be tested using requests from front-end. That will probably take place during the coming Tuesday meeting.

**Comment by ChilliCreek** [comment]
Full stack test conducted and demonstrated during the Thursday presentation on Apr 27.
