### ISSUE TITLE
Registration Page Frontend Javascript

### ISSUE THREAD

**Issue by DarzyD** [abdulkhalil54/Team-Sun#24]
Get the login and registration pages done, so we are done with user authentication.
- [x] Wait for the HTML and stylesheet for the registration page
- [x] Get the request and response specification from the backend team. (get the updated backend_API.txt)
- [x] Implement the HTTP request to the backend.
- [x] Run a full stack test with the backend team.

**Comment by ChilliCreek** [comment]
Finished on Apr 27, full stack test done and demonstrated during presentation. Few bugs might need to be fixed on Chrome.
