### ISSUE TITLE
Schemas for database

### ISSUE THREAD

**Issue by ChilliCreek** [abdulkhalil54/Team-Sun#5]
Once the database is set up, use maintenance.py to set up the tables and their schemas for the account and application storage and retrieval.

**Comment by asingh80** [comment]
First version of the schema for the tables: ![image](https://user-images.githubusercontent.com/128499613/231326749-4e7ee6bc-855e-40b4-a7c2-7e97625475ed.png)

**Comment by ChilliCreek** [comment]
look at database table schema above.
